version: "3"
services:

  front:
    restart: always
    build:
      context: .
      dockerfile: ./front/build/Dockerfile
    ports:
      - 5005:5005
    working_dir: '/root/src'
    volumes:
      - ${FRONT_PATH}:/root/src

    command: gunicorn large_category_page:app

  backend:
    restart: always
    build:
      context: .
      dockerfile: ./backend/build/Dockerfile
    ports:
      - 5006:5006
    working_dir: '/root/src'
    volumes:
      - ${BACKEND_PATH}:/root/src

    command: gunicorn large_category_page:app

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
    ports:
        - 3306:3306
    volumes:
        - db-store:/var/lib
        - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./db/query:/docker-entrypoint-initdb.d 

volumes:
  db-store:


  